### ISSUE TITLE
CLI package resolution throws exceptions for packages that work fine in Unity

### ISSUE THREAD

**Issue by hybridherbst** [openupm/openupm-cli#155]
## Bug report

Running `openupm add org.khronos.unitygltf` results in exceptions in the CLI.  
Running with `-f` works fine and results in a working project.  

See
- https://github.com/KhronosGroup/UnityGLTF/issues/704

#### Bug category

- [x] CLI

#### Steps to reproduce

- Make a project on Unity 2022.3
- Run `openupm add org.khronos.unitygltf`
- Note exceptions in the CLI about package resolution
- Run `openupm add org.khronos.unitygltf -f` and note it actually works fine

We've been using 10.0.0 as dependency forever, and Unity will always auto-upgrade older ShaderGraph versions to the correct built-in version actually available in each specific version of Unity.

#### What is expected?

No error in the openupm CLI, makes it look as if dependencies would be wrong in the package.

#### What is actually happening?

Exception in the CLI

**Comment by favoyang** [comment]
Regarding the reference [https://github.com/openupm/openupm-cli/issues/133](https://github.com/openupm/openupm-cli/issues/133), Unity has ceased using the registry for built-in packages. Now, built-in packages are resolved from the "BuiltInPackages" folder included with the Editor. If there is a version mismatch, it simply gets ignored.

For now, use `-f` until #133 gets fixed.

A test for Unity2022.3.17f1:

![image](https://github.com/openupm/openupm-cli/assets/125390/1c3c00bb-0a9a-455a-bb7b-5db44e8f2ac5)

**Comment by ComradeVanti** [comment]
Does this issue have any difference to #133? If not we could close it right?

**Comment by favoyang** [comment]
> Does this issue have any difference to #133? If not we could close it right?

Yes and no.

`org.khronos.unitygltf` depends on `com.unity.shadergraph@10.0.0`. Because Unity always uses the built-in version shipped with the editor, it will work fine.

#133 wants to resolve this issue. However, `10.0.0` is not an existing version. The only `10.0.x` version (paired with Unity 2020) is `10.0.0-preview.27` and is available on the Unity registry.

Depends on how #133 is implemented
- If we verify the Unity built-in package version strictly (search from the Unity registry, then the version list from [manual docs](https://docs.unity3d.com/Packages/com.unity.shadergraph@10.1/manual/index.html), perhaps reading local editor built-in package folder), the author are required to set a valid version (`10.1.0` for example).
- Otherwise, this issue is fixed if we ignore version verification for Unity built-in packages.

**Comment by favoyang** [comment]
> Depends on how #133 is implemented
> 
> * If we verify the Unity built-in package version strictly (search from the Unity registry, then the version list from [manual docs](https://docs.unity3d.com/Packages/com.unity.shadergraph@10.1/manual/index.html), perhaps reading local editor built-in package folder), the author are required to set a valid version (`10.1.0` for example).
> * Otherwise, this issue is fixed if we ignore version verification for Unity built-in packages.

After reading the implementation of https://github.com/openupm/openupm-cli/pull/364, the built-in package version verification has been bypassed. Then this will be resolved with it.
