### ISSUE TITLE
Question: pkgInfo type

### ISSUE THREAD

**Issue by ComradeVanti** [openupm/openupm-cli#51]
Is the type of `pkgInfo` variables, such as in
```js
// cmd-view.js
let pkgInfo = await fetchPackageInfo(name);
```
the `Packument` type described by [this package](https://github.com/npm/types)?

If not, are there different type definitions for it somewhere?

**Comment by favoyang** [comment]
The `pkgInfo` is the Packument with a few differences:

1. The `getLatestVersion` function looks at the `version` field as a fallback. This may be due to some bad server data.

2. For `PackumentVersion` requires the `unity` field that is filled in by the Verdaccio server for some custom logic.

Overall the naming was very casual when I wrote the project because I didn't notice the npm types repo you mentioned at that time.
